[package]
name = "rhythm_hmm"
version = "0.1.0"
authors = ["Artyom Desyatnikov <l0nikov@ya.ru>"]

[dependencies]
ws = "0.7.1"
serde_json = "1.0.1"
noisy_float = "0.1.2"
rayon = "0.6.0"
env_logger = "0.4.2"
